// TYPES GENERATED BY AN LLM.

declare module '@turbowarp/packager' {
  // ---- Project (returned by loadProject(), set on packager.project) ----
  export interface LoadedProject {
    type: 'sb' | 'sb2' | 'sb3';
    arrayBuffer: ArrayBuffer;
    analysis: {
      usesMusic: boolean;
      [key: string]: unknown;
    };
  }

  export type ProgressCallback = (type: string, loaded: number, total: number) => void;

  /** Must be called before constructing a Packager. Parses the project and downloads assets. */
  export const loadProject: (
    data: Buffer | Uint8Array | ArrayBuffer,
    onProgress?: ProgressCallback,
    abortSignal?: AbortSignal
  ) => Promise<LoadedProject>;

  // ---- Package result ----
  export type PackageTarget = 'html' | 'zip' | 'electron-windows' | 'electron-macos' | 'electron-linux' | 'nwjs-windows' | 'nwjs-macos' | 'nwjs-linux' | 'wkwebview';

  export interface PackageResult {
    project: LoadedProject;

    /**
     * The packaged output. String for 'html', ArrayBuffer for binary targets.
     */
    data: string | ArrayBuffer;
    filename: string;
    type: string; // MIME type
  }

  // ---- Options (mutate individual props, never replace the whole object) ----
  export interface CustomOptions {
    js: string;
    css: string;
  }

  export interface ControlsOptions {
    greenFlag: boolean;
    stopAll: boolean;
    fullscreen: boolean;
  }

  export interface PackagerOptions {
    // Output target
    target: PackageTarget;

    // Runtime behaviour
    turbo: boolean;
    interpolation: boolean;
    framerate: number;
    highQualityPen: boolean;
    maxClones: number;
    miscLimits: boolean;
    fencing: boolean;

    // Stage
    stageWidth: number;
    stageHeight: number;
    stretch: 'none' | 'stage' | 'viewport';

    // UI
    controls: ControlsOptions;
    cursor: 'auto' | 'none';

    // Storage / cloud
    cloudVariables: 'ignore' | 'ws' | 'local' | 'custom';
    cloudVariablesServer: string;

    // Injection
    custom: CustomOptions;

    // Packaging
    compilationLevel: 'none' | 'high' | 'max';
    loaderTheme: string;
    appearanceOptions: {
      override: boolean;
    };

    // Desktop-specific (electron / nwjs)
    app: {
      icon: string | null;
      packageName: string;
      windowTitle: string;
    };
  }

  // ---- Main class ----
  export class Packager {
    project: LoadedProject;
    options: PackagerOptions;

    /**
     * Package the loaded project according to this.options.
     */
    package(): Promise<PackageResult>;
  }

  // ---- Static helpers ----
  export const VERSION: string;
}